Module: ServerlessPatterns.TestableLambda
Items:

  - Function: ApiFunction
    Memory: 1769
    Timeout: 30
    Sources:

      - Api: POST:/posts/preview
        Invoke: PreviewPost

      - Api: POST:/posts
        Invoke: CreatePost

      - Api: GET:/posts
        Invoke: ListPosts

      - Api: GET:/posts/{postId}/view
        Invoke: ViewPost

  - Resource: DataTable
    Scope: ApiFunction
    Allow: ReadWrite
    Description: DynamoDB table
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:

        # Always use string type "S" for keys until you know what you're doing
        - AttributeName: PK
          AttributeType: S

        - AttributeName: SK
          AttributeType: S

      # Always use the same PK/SK schema for all your tables
      KeySchema:
        - AttributeName: PK
          KeyType: HASH

        - AttributeName: SK
          KeyType: RANGE
